from os import environ

YANDEX_FOLDER_ID = environ.get("YANDEX_FOLDER_ID")
YDB_SERVICE_ACCOUNT_KEY_FILE_CREDENTIALS = environ.get("YDB_SERVICE_ACCOUNT_KEY_FILE_CREDENTIALS")
YDB_HOST = environ.get("YDB_HOST")
YDB_PATH = environ.get("YDB_PATH")
YGPT_SERVICE_ACCOUNT_KEY_FILE_CREDENTIALS = environ.get("YGPT_SERVICE_ACCOUNT_KEY_FILE_CREDENTIALS")
LLM_API_BASE = environ.get("LLM_API_BASE")
LLM_API_KEY = environ.get("LLM_API_KEY")
TELEGRAM_BOT_TOKEN = environ.get("TELEGRAM_BOT_TOKEN")